image: node:14.17.6-stretch-slim

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn generate
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

